project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_API_TOKEN
base_path: .
base_url: 'https://lsposed.crowdin.com/api/v2'
pull_request_title: '[translation] Update translation from Crowdin'
preserve_hierarchy: 1
files:
  - source: /manager/src/main/res/values/strings.xml
    translation: /manager/src/main/res/values-%two_letters_code%/%original_file_name%
    type: android
    dest: /manager/strings.xml
targets:
  - name: manager
    sources:
      - /manager/build/outputs/mapping/debug/
    file: /folder/%two_letters_code%/
    format: android
